version: '3.8'
services:

  frontend:
    build:
     context: .
     dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
    - ./frontend:/app
    - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./backend:/app
    - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
